services:
  Redis:
    class: Redis
    calls:
      - method: connect
        arguments:
          - '%env(REDIS_SESSION_HOST)%'

  Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
    arguments:
      - '@Redis'